### PR TITLE
show admin and moderator tags on members list

### LINKED ISSUE #148: On members list, render who is admin / mod

### PR DESCRIPTION
**Pull request by staltz**
Closes #148 

Screenshot from 2021-04-16 13-08-13

### CODE REVIEW

**Comment by cryptix** [comment]
Using the numbers seems a bit bad.

Alternatively you could do `{{if eq .Role.String RoleMember}}`.

Not sure if it needs a test but would be bad to regress on.

**Comment by cryptix** [comment]
Using the numbers seems a bit bad.

Alternatively you could do `{{if eq .Role.String RoleMember}}`.

Not sure if it needs a test but would be bad to regress on.

**Comment by staltz** [comment]
Great! I actually tried `{{if eq .Role "RoleAdmin"}}` and it didn't work. The trick was `.Role.String` :ok_hand: 

(Updated the PR)

**Comment by staltz** [comment]
Added tests

**Review by cryptix — APPROVED** [review]
nice! thanks for adding the tests, too.

SGTM

**Pull request merged**
