### PR TITLE
German translation

### PR DESCRIPTION
**Pull request by pathab**
Probably not perfect, but much better than before. I have already tested it on my server. There are still some texts that cannot be translated with the file (e.g. alias page). If new keys are added, I will be happy to update them. I'm looking forward to the further updates :-)

### CODE REVIEW

**Comment by pathab** [comment]
#254 can be resolved with this translation-file.

**Comment by cryptix** [comment]
> There are still some texts that cannot be translated with the file (e.g. alias page).

sorry, not sure i get this part..?

> If new keys are added, I will be happy to update them.

I don't think we plan to do so anytime soon. :)

otherwise looks great and I'd merge?

**Comment by pathab** [comment]
image

Alias Page: Here I didn't find the corresponding key to translate.

**Comment by staltz** [comment]
I'll merge based on cryptix's comment "otherwise looks great and I'd merge".

Thanks for your contribution!

**Pull request merged**
