### PR TITLE
style the invite-list page

### PR DESCRIPTION
**Pull request by staltz**
I'm keeping this PR focused on just one page, I'll make other PRs for each other page. I'm not entirely confident about the layout I made here, when we find a potentially better layout, we can change it.

Screenshot from 2021-03-12 13-24-29

### CODE REVIEW

**Comment by staltz** [comment]
PS @cryptix some ideas I stumbled upon while making this: (1) it would be useful to have a field "CreationDate" on the Invite model, so moderators on this page can know which invites are old (and probably could be revoked) and which are young, (2) I noticed that the alias suggestion doesn't have to be unique, maybe we could attach this invite logic to the alias database so that you cannot suggest an alias that is already taken (either by an actual alias registration, or taken in another invite as an alias suggestion). Ideas for others issues/PRs.

**Comment by cryptix** [comment]
Yup, those are both good suggestions. The created time is a total no brainer and oversight.

Re alias suggestion: I thought of that but wanted to have the alias system in place first before doing this.

**Comment by cryptix** [comment]
Re the layout: do we show the IDs on the other pages? I don't think users need to see those.

Other then that, it fits the vibe of the rest.

I think on the members list the add/create thing is under the heading?

These are the only inconsistencies I noticed.

**Comment by staltz** [comment]
> Re alias suggestion: I thought of that but wanted to have the alias system in place first before doing this.

Oh right

> Re the layout: do we show the IDs on the other pages? I don't think users need to see those.

It's useful just to disambiguate the invite codes in case you created N invites with no aliases. If we have the CreationDate, we could remove the IDs.

> I think on the members list the add/create thing is under the heading?

I know, it's a different design here, it's a bit different concepts. Members list is about including known IDs, this one is about creation (where design references I've seen on Dribbble typically put outside of the table itself).

**Comment by cblgh** [comment]
👍 

looks great :) does it work nicely on phones as well? i don't speak tailwind :~

**Comment by cryptix** [comment]
oh and this updates #68, too :smile_cat:

**Review by cryptix — APPROVED** [review]

**Comment by staltz** [comment]
> +1
> 
> looks great :) does it work nicely on phones as well? i don't speak tailwind :~

I'll check! Good reminder

**Comment by staltz** [comment]
Ok, it's all broken on mobile screen sizes. I'll fix that

**Comment by staltz** [comment]
Ok, now it's like this:

| Mobile | Desktop |
|----|----|
| Screen Shot 2021-03-12 at 16 55 48 | Screenshot from 2021-03-12 16-55-54 |

**Comment by staltz** [comment]
Can haz merge? :cat2:

**Comment by cryptix** [comment]
Very nice! Go ahead!

**Pull request merged**
